### ISSUE TITLE
Create release

### ISSUE THREAD

**Issue by sbjoshi** [GoodDeeds/Timetabler#1]
@GoodDeeds  Please create a release of a stable version. The changes regarding Tseitin encoding etc can be done later.

**Comment by GoodDeeds** [comment]
@sbjoshi Sir, the release has been created, and can be viewed [here](https://github.com/GoodDeeds/Timetabler/releases/tag/v0.1.0). We will add more examples as well.
Code documentation can be found at [http://timetabler.readthedocs.io](http://timetabler.readthedocs.io).
