### ISSUE TITLE
Weights corresponding to custom constraints are not added correctly

### ISSUE THREAD

**Issue by prateekkumarweb** [GoodDeeds/Timetabler#10]
- [x] SAME, NOT SAME Bug
- [x] Weights assigned to custom constraints Bug

**Comment by prateekkumarweb** [comment]
Fixed SAME, NOTSAME custom constraints bug.

**Comment by GoodDeeds** [comment]
Weights for predefined constraints fixed in [cb53c27](https://github.com/GoodDeeds/Timetabler/commit/cb53c27dc9d1d00ee6e783d118a6a6d849d9ead4).

Weights for custom constraints fixed in [3deef5a](https://github.com/GoodDeeds/Timetabler/commit/3deef5a5bc45088177c3a79a54845e590f13cd66)
