### ISSUE TITLE
Remove IITH specific statement in the description

### ISSUE THREAD

**Issue by sbjoshi** [GoodDeeds/Timetabler#21]
On the project homepage "GoodDeeds/Timetabler" under the "<>Code" tab one see the following statement

"
Encode timetabling constraints as a SAT formula and solve using a MaxSAT solver to generate a Timetable for IITH https://timetabler.readthedocs.io"

The tool can be used to generate timetable for any weekly schedule. It may be good to remove the word "IITH" as it gives the wrong impression that the scope of this tool is limited for IITH fractal system only.

**Comment by GoodDeeds** [comment]
@sbjoshi This has been updated.

**Comment by prateekkumarweb** [comment]
@GoodDeeds Also needs to be updated in the description in CMakeLists.txt file.
