### ISSUE TITLE
What is segments in Fields.yml .

### ISSUE THREAD

**Issue by Siddiq200** [GoodDeeds/Timetabler#3]
Please, Add a little description, what are Segments ?  What is the use of segments ?

**Comment by prateekkumarweb** [comment]
@Siddiq200 This software is specifically designed for [IIT Hyderabad](https://iith.ac.in). IIT Hyderabad follows fractal academics. Each semester is divided into some number of segments. In `fields.yml`, you specify the start and end index of the segments.

At IIT Hyderabad, we have 6 segments, hence the configuration is
```yaml
segments:
  start: 1
  end: 6
```

**Comment by Siddiq200** [comment]
but In an input example file"testinput.csv"
name,class_size,instructor,segment,is_minor,CS14B,CS15B,CS16B,CS17B,CS15M,CS16M,CS17M,PHD,classroom,slot
CS3550,40,Manohar Kaul,56,No,No,Core,No,No,No,No,No,No,,
CS6250,40,Ramakrishna Upadrasta,16,No,Elective,No,No,No,No,Elective,Elective,Elective,,A

value of segment is like 56 and 16.
I want to modify the Project according to "The University of Lahore". That is why I am trying to understand deeply. 

Please Help!
