### ISSUE TITLE
Unclear terminology

### ISSUE THREAD

**Issue by aeria** [GoodDeeds/Timetabler#41]
It is not clear to me what a Course is versus a Program
Or a time versus a Slot.
Can these be explained better?

**Comment by prateekkumarweb** [comment]
This software is for scheduling timetable in a University/College/School like setting. Here is an example of all the terminologies:
```
course: CS101 (Programming)
program: B. Tech. 1st year (Bachelor of Technology First Year students)
slot: Mon 10:00 am to 12:00 noon (A time slot where a course can be scheduled)
```

I am closing this issue as there is already an issue regarding documentation open and I will add a TODO to improve documentation to that issue.
