### ISSUE TITLE
Use Tseitin encoding to decrease memory usage

### ISSUE THREAD

**Issue by Siddiq200** [GoodDeeds/Timetabler#6]
```
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
Aborted (core dumped)
```

What is the reason of this ERROR.

I entered 50 courses and slots and teachers are enough. but while adding constraints the process is terminated.

Thanks in advance.

**Comment by GoodDeeds** [comment]
@Siddiq200 This issue has been fixed.
